apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  - name: "8030"
    port: 8030
    targetPort: 8030
  selector:
    service: reverseproxy
  type: LoadBalancer